rename voice_assistant.state to agent.state
livekit/agents pull request #772
Opened 2024-09-17 19:54 UTC by bcherry

Following conversation in Slack.

See https://github.com/livekit/components-js/pull/976 as well

2024-09-17 19:58 UTC, theomonnom commented on livekit-agents/livekit/agents/proto.py
> +AgentState = Union[Literal["initializing", "listening", "thinking", "speaking"], str]
kk make sense, let's make sure we never expose the file itself, only the content

2024-09-17 19:59 UTC, theomonnom approved these changes

2024-09-17 20:04 UTC, bcherry commented on livekit-agents/livekit/agents/proto.py
> +AgentState = Union[Literal["initializing", "listening", "thinking", "speaking"], str]
yeah i think that's what's done in the main `__init__.py`? also I just updated it to put the attr name into a constant too, lmk if i did this in the most pythonic way or not!

2024-09-18 08:15 UTC, lukasIO commented
Are we expecting users to add custom states directly to the `VoiceAssistant` class ? 
If we do, we should make `_update_state` a public method. 
If not, it might make sense to keep `VoiceAssistantState` as a narrowed down type of `AssistantState` where assistant state could consist only of either `str` or some more generally applicable states than `listening` and `speaking` - which sound very much voice-only related.

2024-09-18 18:20 UTC, bcherry commented
> Are we expecting users to add custom states directly to the `VoiceAssistant` class ? If we do, we should make `_update_state` a public method. If not, it might make sense to keep `VoiceAssistantState` as a narrowed down type of `AssistantState` where assistant state could consist only of either `str` or some more generally applicable states than `listening` and `speaking` - which sound very much voice-only related.

yeah that could make sense - i think that would be easy to change later as we think through it so i'm going to merge this once the tests pass

2024-09-18 18:28 UTC, nbsp requested changes

2024-09-18 18:28 UTC, nbsp commented on .changeset/curly-rats-burn.md
> +"livekit-agents": patch
```suggestion
"livekit-agents": minor
```

2024-09-18 19:56 UTC, lukasIO commented
>  i think that would be easy to change later as we think through it

if we choose to narrow down a type lateron, I think that will be a breaking change?

2024-09-18 20:18 UTC, bcherry commented
> > i think that would be easy to change later as we think through it
> 
> if we choose to narrow down a type lateron, I think that will be a breaking change?

in this version, VoiceAssistantState (as a type) doesn't exist at all in the public parts of the framework - it's all internal.

2024-09-18 20:37 UTC, bcherry commented
@theomonnom and I discussed offline and decided it would be a good idea to use a `lk.` prefix on attributes we define, to avoid collisions with user-defined attributes.

2024-09-18 20:43 UTC, lukasIO commented
> in this version, VoiceAssistantState (as a type) doesn't exist at all in the public parts of the framework - it's all internal.

makes sense, but we do expose the changed name in https://github.com/livekit/components-js/pull/976

2024-09-18 20:53 UTC, bcherry commented
> makes sense, but we do expose it in [livekit/components-js#976](https://github.com/livekit/components-js/pull/976)

yeah the values are exposed but not the constrained python type. but maybe i misunderstood your suggestion - were you thinking it's good to keep the `voice_assistant.state` attribute too? in addition to a `agent.state` attribute that has less granularity?

2024-09-18 21:48 UTC, merged